name: Test

on:
  push:
    branches:
      - main
      - staging
  pull_request:

env:
  RUBY_VERSION: 3.3.9
  NODE_VERSION: 18.17.1
  CHROME_VERSION: "119.0.6045.105"
  RAILS_ENV: test
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: localhost

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install additional tools
        run: sudo apt-get update && sudo apt-get install -y imagemagick p7zip

      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: ${{ env.CHROME_VERSION }}

      - name: Remove Chrome
        run: sudo apt remove google-chrome-stable

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ env.CHROME_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Setup & create Database
        run: |
          DISABLE_SPRING=1 bundle exec rails db:create db:schema:load

      - name: Precompile assets
        run: |
          npm ci
          bundle exec rake assets:precompile

      - name: Run RSpec
        run: SIMPLECOV=1 CODECOV=1 bundle exec rspec
        env:
          CAS_HOST: cas.example.org
